const notes = [
	{
		title: "To-Do",
		description: "Today's Tasks",
		content: "- Finish UI design\n- Update documentation\n- Push to GitHub",
		footer: "Due Today",
		cardBackgroundColor: "bg-blue-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-blue-800 font-bold",
		cardContentColor: "text-blue-700",
		cardFooterColor: "text-blue-600 text-sm",
		cardPosition: "absolute top-10 left-[20%] rotate-[0deg]"
	},
	{
		title: "Meeting Notes",
		description: "Project kickoff",
		content:
			"Discuss timelines, assign roles, and finalize resources  Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources Discuss timelines, assign roles, and finalize resources.",
		footer: "Updated 2 hrs ago",
		cardBackgroundColor: "bg-yellow-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-yellow-800 font-bold",
		cardContentColor: "text-yellow-700",
		cardFooterColor: "text-yellow-600 text-sm",
		cardPosition: "absolute top-20 left-[40%] rotate-[0deg]",
		large: true,
	},
	{
		title: "Reminder",
		description: "Team Lunch",
		content: "Don't forget the lunch meeting at 1 PM.",
		footer: "Location: Cafe Central",
		cardBackgroundColor: "bg-pink-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-pink-800 font-bold",
		cardContentColor: "text-pink-700",
		cardFooterColor: "text-pink-600 text-sm",
		cardPosition: "absolute top-30 left-[60%] rotate-[deg]",
	},
	{
		title: "Ideas",
		description: "Brainstorming Session",
		content: "New feature ideas and improvements",
		footer: "Next meeting: Friday",
		cardBackgroundColor: "bg-green-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-green-800 font-bold",
		cardContentColor: "text-green-700",
		cardFooterColor: "text-green-600 text-sm",
		cardPosition: "absolute top-40 left-[60%] rotate-[0deg]",
	},
	{
		title: "Quick Notes",
		description: "Random thoughts",
		content: "Remember to check the server logs for errors.",
		footer: "Last updated: 3 days ago",
		cardBackgroundColor: "bg-gray-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-gray-800 font-bold",
		cardContentColor: "text-gray-700",
		cardFooterColor: "text-gray-600 text-sm",
		cardPosition: "absolute top-50 left-[80%] rotate-[10deg]",
		large: true,
	},
	{
		title: "Project Updates",
		description: "Weekly progress",
		content: "Completed tasks and next steps",
		footer: "Reviewed by the team",
		cardBackgroundColor: "bg-purple-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-purple-800 font-bold",
		cardContentColor: "text-purple-700",
		cardFooterColor: "text-purple-600 text-sm",
		cardPosition: "absolute top-60 left-[120%] rotate([-20deg])",
	},
	{
		title: "Feedback",
		description: "User feedback and suggestions",
		content: "Collect feedback from users about the new features.",
		footer: "Next review: Monday",
		cardBackgroundColor: "bg-orange-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-orange-800 font-bold",
		cardContentColor: "text-orange-700",
		cardFooterColor: "text-orange-600 text-sm",
		cardPosition: "absolute top-70 left-[14%] rotate([20deg])",
	},
	{
		title: "Personal Notes",
		description: "Thoughts and reflections",
		content: "Take time to reflect on personal growth and goals.",
		footer: "Keep it private",
		cardBackgroundColor: "bg-teal-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-teal-800 font-bold",
		cardContentColor: "text-teal-700",
		cardFooterColor: "text-teal-600 text-sm",
		cardPosition: "absolute top-80 left-[16%] rotate([-30deg])",
	},
	{
		title: "Learning",
		description: "New skills to acquire",
		content: "Explore new programming languages and frameworks.",
		footer: "Resources available",
		cardBackgroundColor: "bg-indigo-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-indigo-800 font-bold",
		cardContentColor: "text-indigo-700",
		cardFooterColor: "text-indigo-600 text-sm",
		cardPosition: "absolute top-90 left-[18%] rotate([30deg])",
	},
	{
		title: "Health",
		description: "Wellness tips and reminders",
		content: "Stay hydrated and take regular breaks.",
		footer: "Self-care is important",
		cardBackgroundColor: "bg-lime-100",
		cardBorderColor: "border-transparent",
		cardTitleColor: "text-lime-800 font-bold",
		cardContentColor: "text-lime-700",
		cardFooterColor: "text-lime-600 text-sm",
		cardPosition: "absolute top-100 left-[20%] rotate([-40deg])",
	},
];

export { notes };
